EMA_PERIOD        = 20
VOLUME_AVG_PERIOD = 20
RVOL_THRESHOLD    = 2.0
BODY_RATIO_MIN    = 0.60
MIN_PRICE         = 100
MIN_AVG_VOLUME    = 500000
TOP_N_RESULTS     = 10

TV_USERNAME = ""
TV_PASSWORD = ""
TV_EXCHANGE = "NSE"
TV_LOOKBACK_BARS = 60

OUTPUT_DIR   = "/Users/anandkiruthi/NSEScanner/outputs"
CSV_FILENAME = "breakout_signals.csv"

TELEGRAM_ENABLED   = False
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN"
TELEGRAM_CHAT_ID   = "YOUR_CHAT_ID"

NSE_SYMBOLS = [
    "RELIANCE","TCS","HDFCBANK","INFY","HINDUNILVR","ICICIBANK","KOTAKBANK","SBIN",
    "BAJFINANCE","BHARTIARTL","ASIANPAINT","AXISBANK","MARUTI","TITAN","LT","WIPRO",
    "ULTRACEMCO","SUNPHARMA","NESTLEIND","ONGC","NTPC","POWERGRID","M&M","TECHM",
    "HCLTECH","BAJAJFINSV","ADANIPORTS","DIVISLAB","GRASIM","HINDALCO","EICHERMOT",
    "BPCL","DRREDDY","CIPLA","JSWSTEEL","TATACONSUM","COALINDIA","INDUSINDBK",
    "TATASTEEL","APOLLOHOSP","HDFCLIFE","SBILIFE","BRITANNIA","HEROMOTOCO",
    "BAJAJ-AUTO","ZYDUSLIFE","PERSISTENT","MPHASIS","COFORGE","LTIM","TRENT",
    "DMART","POLYCAB","BANKBARODA","FEDERALBNK","IDFCFIRSTB","PFC","RECLTD",
    "IRCTC","CONCOR","ZOMATO","IRFC","RVNL","HAL","BEL","ADANIGREEN",
    "TATAPOWER","CHOLAFIN","MANAPPURAM","MUTHOOTFIN","CANBK","YESBANK",
    "IGL","MGL","PETRONET","IOC","HINDPETRO","AMBUJACEM","ACC","RAMCOCEM",
    "CGPOWER","BHEL","KALYANKJIL","PIDILITIND","BERGEPAINT","ASTRAL",
]
